services:
  localstack:
    image: localstack/localstack:2.1
    environment:
      - SERVICES=lambda,s3,dynamodb,apigateway,logs
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DEFAULT_REGION=us-east-1
    ports:
      - "4566:4566"
      - "4571:4571"
    volumes:
      - localstack_data:/tmp/localstack/data
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  localstack_data:
